### ISSUE TITLE
Max deposit reached, despite availability

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#107]
![unable to bank](https://github.com/OpenThrone/OpenThrone/assets/132112018/5470955a-210a-452c-8058-f1ad6a5abd0d)

Im told I have 3 deposits, has some other update prohibited my banking ability? If so, what are the exact time details of that stipulation.
i.e. Max 1 deposit every 12 hrs?

**Comment by uaktags** [comment]
Nope, it's 3 per 24hours for your current level:

![image](https://github.com/OpenThrone/OpenThrone/assets/893684/9c140ae3-91f6-4c5d-8ba4-9b224ba7ba25)

So it looks like you may be in that 24hour limit right now, depending on the exact second you tried submitting that deposit

However, the deposits available looks off

**Comment by uaktags** [comment]
okay, looks like there's a backend issue causing a discrepancy between the displayed amount available and the backend. This is new due to a validation check and has been corrected. Let me know if you're still having an issue.

Did a small test to ensure its working, you'll see a deposit of 1337 and i also threw some extra gold into the bank ;-)
