### ISSUE TITLE
correct unit loss after battle?

### ISSUE THREAD

**Issue by Dimez123** [OpenThrone/OpenThrone#111]
![unit loss](https://github.com/OpenThrone/OpenThrone/assets/132112018/a9c82bb9-4676-4b82-9207-c83e7c756559)
![image](https://github.com/OpenThrone/OpenThrone/assets/132112018/8d9f85b0-23b7-4a5b-bd24-70ea704ee007)

Should an attacker lose units when the defender does 0 def dmg? Indicating no def units are trained?

"Now, citizens, workers, spies, and sentries are at risk of death if the defender has no defense units."

Follow up question, Is the only way to keep your population safe to untrain all units? Does this mean if someone wants to take a break from the game they're at risk of total population loss from either a lack of defenders or from having your fort destroyed and essentially losing their entire population in an attack?

**Comment by uaktags** [comment]
Yes to both you should expect some resistance from Citizens, Workers, Spies, and Sentries if you breach a fort and that you will take deaths.

Please note, as mentioned in that ticket, the math is still being worked on.

And to the last question, absolutely, there is no way to just leave the game and expect the army to stay safe. There's 0 reason for the game to be littered with "log in, train offense, attack, untrain offense, train workers/or don't, log off". It removes the entire purpose of the game and only encourages bot play.

Perhaps a vacation mode is what a user that needs a break is looking for?

**Comment by Dimez123** [comment]
Ticket related question: So the only method to protect yourself from losing nearly all progress is to 24/7 monitor your fort health?

Ignorable opinion-based complaining: I'm not saying your army becomes safe, but your workers or even untrained citizens being killed upon fort breach was more than I expected. While likely in conjunction with the original DT gameplay, if that happens once your account is effectively neutered.

If that's the direction of the game then that's the developer prerogative. Though I know folks like Nunos probably have hundreds if not thousands of attack turns saved up. It would only take him maybe ~12-15 turns at 10 attacks over a 60 second time period to effectively zero out my progress...that's the risk of the game I guess but I know once that happens I'd stop playing. I do hope the game gets bigger but I'm unsure if that near-complete death that can happen overnight or within a bathroom break will encourage player retention.

**Comment by uaktags** [comment]
I don't agree that it should be an ignorable opinion, I think it drives the conversation to hopefully find a good balance. I think discussions should be had on how to combat this out the gate. For instance, perhaps in the early levels, more leniency should be in place to not wipe your units, either defense or not. Or maybe civilian casualties are even more fractional than they are or get more worse as we level up.

The stance I stand firm on though is ghost/bot armies. It's just no fun for anyone to never have a target because the accounts around you are all civilian/offense/spy/etc. the issue here though is how to balance that.

As for vacation, no I personally don't see it as a need, but that's why this system of making issues and discussing it is paramount. If there is a need for it, just create an issue, work it out, and then as time permits I can put some cycles into it. Just off the cuff, some "issues" that I think would need to be figured out is: what's the limit on usage/requests for vacation, should it cost anything, what happens to your Overall rank upon return, what happens to you upon return (you've been away for 5days and everyone around you has grown their armies for 5days), etc. it's these discussions that lead to testing and code production.

**Comment by NunosDC** [comment]
When the game goes live one player will only be able to perform 5 attacks in a 24 hour period so no single player will be able to destroy your account in 60 seconds. One of the problems in DT was that people were making Ghost accounts this helps address that some because alliances will be able to get an annoying account into fort breach then anyone else in the alliance can destroy that account.
It should be easy enough to keep fort repaired and/or maintain some defense.

**Comment by uaktags** [comment]
> When the game goes live one player will only be able to perform 5 attacks in a 24 hour period 

This was supposed to have been fixed last week, but looks like a code issue left it there. Fixed now

**Comment by Dimez123** [comment]
Fair enough
