### ISSUE TITLE
Recruitment still broken?

### ISSUE THREAD

**Issue by MarkTraceur** [OpenThrone/OpenThrone#162]
#158 is closed, but I don't think it's fixed. Live site's community stats tab shows that only three users have recruited the full amount in the past 24 hours. I personally haven't been able to for the past 24 hours for sure, possibly longer (I haven't been keeping good track).

**Comment by uaktags** [comment]
So to be clear on the intended workflow:
- Days are considered from 04:00:00Z-03:59:59Z everyday (GMT -4 or EDT timezone)
- HandleRecruitment and GetRandomUser apis are checking to make sure that the clicks are GTE to OTStartDate which gets the start of the current date (server side, so midnight starting of current date for server).
- So in theory, the following test should work:
If a user clicks 5x at 11:50PM EDT on Aug 11th this is recorded as Aug 12 03:50:00Z
If a user tries to do a 6th check at 11:51PM EDT, the server should return that OTStartDate is Aug 11 00:00 EDT or 04:00:00Z, so it should fail due to >= 5 recruitments
If a user tries to do a 6th recruit at 00:01AM EDT on Aug 12 (10minutes later), the server should return that OTStartDate is Aug 12 00:00EDT or 04:00:00Z, the total recruitments should be 0, and the recruit should go forth.

I'll work on a unittest to add in to ensure this is playing out correctly

**Comment by LordMike13** [comment]
Hello, good day, if you allow me to comment, I think it is more appropriate to send a message or notification when you can recruit, so as not to be speculating with unnecessary clicks. Greetings and long live the OT team:.

**Comment by MarkTraceur** [comment]
See #163 for the fix - apologies for the inconvenience, we are working on getting a fix on the go :)

**Comment by MarkTraceur** [comment]
Fix merged, and it should be working now - I'll close tomorrow once we verify that, if nobody else beats me to it!

**Comment by uaktags** [comment]
I think we're finally good to go on this. going to leave up for a few more hours.
