### ISSUE TITLE
missing citizens

### ISSUE THREAD

**Issue by Terrifier96** [OpenThrone/OpenThrone#214]
hello, i signed in today and noticed that all of my citizens are gone. ever since the owners let anyone attack me i cant keep any gold and have not wanted to play, so i untrained all workers and just check every now and then. i haven't been attacked after that, so no one killed them. can someone look at this and return my citizens please? and when will the attack anyone be turned off? i cant do anything if big accounts like revenate attack me 3 times a day

**Comment by uaktags** [comment]
Yep, we're aware of the bug and announced it in discord, and have since patched it.
You lost about 15k Citizens but the actual original count is unknown at this time. I can return those, i just didn't want to until we saw you log back in again.

The attack system will remain until we reset as we're still working through numerous issues to get things stable and iron out the final details. With users using github more, we finally have better sight on the issues plaguing users.
