### ISSUE TITLE
Should Overall Rank be separate from Users page ranking

### ISSUE THREAD

**Issue by uaktags** [OpenThrone/OpenThrone#215]
So tied with the discussion #179, i think it warrants revisiting how we display users "rank" in the Users' page.

Right now, in OT, we use OR for both your overall rank and your placement in the Battle Users page. This leads to the weights we've been using to be heavier in XP, and giving less credit to other factors that are equally warranted.

In reviewing the archive we have of DT taken by Matt we can see that OR and your Rank on the User's page to be separate:
![image](https://github.com/user-attachments/assets/d3f1aba1-f7ae-47ad-96cf-382ee6ed127b)
and 
![image](https://github.com/user-attachments/assets/c918963e-8955-4e07-89ba-97d1ada1eb0b)

In looking at other games for inspiration, such as LoC, we can see a similar occurance:
![image](https://github.com/user-attachments/assets/7cc1fd83-c57b-4f8e-ae9a-4f6c6549b6e2)
vs (their battle listings page doesn't actually take you to the page you reside, and im not going to go search for myself) 
![image](https://github.com/user-attachments/assets/3bcb6ae3-516b-49d4-a845-ce64f003f7b1)

So...that brings us at an ultimatum. We can keep with the OT way of combining these two stats and limit the flexibility to calculate Overall Rank, or we can separate them. The #1 person on the /battle/users page is the highest XP person, but may not be the highest OR person.

**Comment by Revenate39** [comment]
I think separating them is a great way to go, that way the attack page is listed by XP rank (more XP = higher rank).
Also having the title changed to 'XP rank' I think makes a great deal of sense, and hopefully stops people getting upset about being a lower XP rank compared to an account where they have better stats.

This is where OR comes in, and brings together the stats that are decided in discussion #179
My only comment around OR, is that it feels a bit hidden, only being listed on each individual accounts profile page. Could OR be a filter on the attack page, or maybe even slapped onto the overview page, 'Revenate is an ELF ASSASSIN and has an OR ###'

**Comment by uaktags** [comment]
>Could OR be a filter on the attack page, or maybe even slapped onto the overview page, 'Revenate is an ELF ASSASSIN and has an OR ###'

I think all 3 or a combination of are certainly easy changes to add in.

**Comment by JOHNNYGAZER** [comment]
IMO the users page should auto-sort by XP since typically you're looking at these pages to attack and grouping by attackable targets makes sense. This should be it's own separate experience rank in the scoreboard as well. For OR, I actually would prefer if experience was entirely removed from that calculation and account wealth, offense, defense, and unit value scores were used instead. One thing that I did like in DT Beta was having the two different ranks to reward both types of players: folks who were aggressive active attackers and those who were slower and more calculated builders. In that system, people are still incentivized to level up to acquire upgrades and points to add to their stats, but it isn't 100% necessary to get a /decent/ overall rank.

Also @uaktags you may want to take another look at the wealth stat. I don't think that it's taking into account battle upgrades.

**Comment by uaktags** [comment]
let's keep the OR calculation stuff to the other one lol 
Just need to keep this focused on what to do with the Users' page ranking on this issue, and this will close leaving the other issue open for deciding that stuff.

So looking like to keep users page to just xp.

**Comment by Dragonsoulj** [comment]
I'll agree with Johnny here: The user list being sorted by XP makes the most sense since you can only attack those within your level range, and that's determined by XP. Ideally, I'd say sort by Level (not XP) then OR so you have your target levels around you to fit the range requirement, and then the hardest or easiest targets since OR is a better show of strength than XP alone. I almost feel like this was how it was done back in Beta, but I can't remember.

**Comment by uaktags** [comment]
For now, i'll go with just the XP ranking just to move the progress along. After that I can set up a number of tests to show the different ideas on how to sub-sort the users differently
