### ISSUE TITLE
Attack turns pillage percentage

### ISSUE THREAD

**Issue by camarao69** [OpenThrone/OpenThrone#249]
Hello

I have already speaked to Taco about  this over on discord but just to not forget I decided to post it here.

The percentage o pillage is always the same, 75% regardless of the number of turns you use, the value of the pillages would increase whenever more turns are used maxing out at 10 turns.

**Comment by JOHNNYGAZER** [comment]
I'm actually curious how others think this should scale since, I think, fort damage, experience and casualties scale up with attack turns. I like the idea of gold scaling up quicker than that so that attacking for gold does less damage to the defender vs attacking for experience or damage to the defending player. Seems like a reasonable way to gather gold without making too many enemies, plus there is built-in counterplay by simply _logging in before anyone attacks you_.

That being said, 75% of total defender gold for 1 turn does seem to be a little imbalanced in terms of value. I would personally like to see something like 50+(3*turns used)%.

**Comment by camarao69** [comment]
> I'm actually curious how others think this should scale since, I think, fort damage, experience and casualties scale up with attack turns. I like the idea of gold scaling up quicker than that so that attacking for gold does less damage to the defender vs attacking for experience or damage to the defending player. Seems like a reasonable way to gather gold without making too many enemies, plus there is built-in counterplay by simply _logging in before anyone attacks you_.
> 
> That being said, 75% of total defender gold for 1 turn does seem to be a little imbalanced in terms of value. I would personally like to see something like 50+(3*turns used)%.

Actually I do agree with this , I just posted this issue because I as always doing 10 turn attacks to max pillage not knowing 1 was enough.

**Comment by uaktags** [comment]
Currently, the bug is that 75% is always the value, so it's failing to scale. The scale will be fixed in the upcoming patch this week.

**Comment by Revenate39** [comment]
Quick question what does the scaling look like?
Just looking to understand what is the best value for gold pillaged vs xp gained
