### ISSUE TITLE
Can´t untrain

### ISSUE THREAD

**Issue by LordMike13** [OpenThrone/OpenThrone#256]
![imagen_2024-10-15_101716378](https://github.com/user-attachments/assets/fabdeb5c-df48-46eb-b7ed-7d2c70d05839)

**Comment by uaktags** [comment]
I need more information than the error message.
The error is saying that there's a value in the Royal Guards. If this isn't true, gotta make that known in the issue. 
Right click on the page, Inspect Element, go to network, and then click the 'untrain all' button after incrementing the amount of units and which types you want. You'll see an entry like this:
![image](https://github.com/user-attachments/assets/913148f0-bebc-4fe0-8c96-063977083be1)

provide me with the payload and the error message.

**Comment by uaktags** [comment]
For reference, the payload is just going to show the values being passed to the server, so i'm hoping to see that Defense is 0 which would indicate the error is in the backend, or it'll show a number for quantity indicating a frontend issue.

**Comment by LordMike13** [comment]
![imagen_2024-10-15_103357238](https://github.com/user-attachments/assets/3f90ad6d-119e-4ce7-a139-fce2119528fb)

**Comment by uaktags** [comment]
Thanks, so points to backend. Looks like it has to do with the fact that you've never trained a Defender Level 3, so that value isn't in your units blob and harderrors. A patch is being created now for this to not hard-error. In the meantime, you can try training 1 level 3 defender and then untrain it. Otherwise, i'll update here when the patch goes live.

**Comment by LordMike13** [comment]
Thank you very much for your support, as soon as I generate citizens I will proceed with the suggested operation.
