### ISSUE TITLE
Issue with TextMatching

### ISSUE THREAD

**Issue by BronzeMantis** [OpenThrone/OpenThrone#46]
I get this when refreshing a page.
![UnRun](https://github.com/OpenThrone/OpenThrone/assets/150398391/955bdcdf-0763-44b9-953b-8a1278cd130e)
![unrun2](https://github.com/OpenThrone/OpenThrone/assets/150398391/7115333a-5933-4cea-a805-2f88fe2fab14)

**Comment by uaktags** [comment]
Interesting, the issue should be temporary due to the year change now, but it means somewhere i still have data that isn't being formatted correctly. I'll have to dig through.

**Comment by BronzeMantis** [comment]
I've had a few of these today, on the recruiter, the bank and the armoury. It said something about collapse in the runtime error and I don't know if it's a coincidence as the armoury wouldn't display fully but partially like a collapse. I didn't take a screenshot of the armoury as I hoped it would only be temporary and it was; but I can't access the bank still. 
Screenshot of bank error - 
![unrun3](https://github.com/OpenThrone/OpenThrone/assets/150398391/ea8847cc-9926-464b-a9ef-5af5afc52f83)

**Comment by BronzeMantis** [comment]
Broken not blank

**Comment by uaktags** [comment]
No i understand, I moved it to #47 since its unrelated. This was one of a few issues where pages today were broken like you saw, or blank like on the Structures/Upgrades page earlier today. Those issues are related to eachother, but they're unrelated to the Text not matching issue you originally posted. So just separated them.
